import {
  Achievement,
  AchievementCategory,
  AchievementType,
} from '../entities/achievement.entity';

export const achievementSeeds: Partial<Achievement>[] = [
  // Conquistas Sociais
  {
    name: 'Primeiro Amigo',
    description: 'Faça sua primeira conexão no Superese',
    category: AchievementCategory.SOCIAL,
    type: AchievementType.FRIEND_CONNECTIONS,
    targetValue: 1,
    iconKey: 'first_friend',
    isActive: true,
  },
  {
    name: 'Círculo Social',
    description: 'Conecte-se com 5 pessoas',
    category: AchievementCategory.SOCIAL,
    type: AchievementType.FRIEND_CONNECTIONS,
    targetValue: 5,
    iconKey: 'social_circle',
    isActive: true,
  },
  {
    name: 'Rede de Apoio',
    description: 'Conecte-se com 10 pessoas',
    category: AchievementCategory.SOCIAL,
    type: AchievementType.FRIEND_CONNECTIONS,
    targetValue: 10,
    iconKey: 'support_network',
    isActive: true,
  },
  {
    name: 'Primeira Interação',
    description: 'Curta ou comente em um post pela primeira vez',
    category: AchievementCategory.SOCIAL,
    type: AchievementType.FORUM_INTERACTIONS,
    targetValue: 1,
    iconKey: 'first_interaction',
    isActive: true,
  },
  {
    name: 'Participante Ativo',
    description: 'Realize 25 interações no fórum',
    category: AchievementCategory.SOCIAL,
    type: AchievementType.FORUM_INTERACTIONS,
    targetValue: 25,
    iconKey: 'active_participant',
    isActive: true,
  },
  {
    name: 'Engajador Social',
    description: 'Realize 50 interações no fórum',
    category: AchievementCategory.SOCIAL,
    type: AchievementType.FORUM_INTERACTIONS,
    targetValue: 50,
    iconKey: 'social_engager',
    isActive: true,
  },
  {
    name: 'Post Popular',
    description: 'Tenha um post que receba pelo menos 10 curtidas',
    category: AchievementCategory.SOCIAL,
    type: AchievementType.POPULAR_POST,
    targetValue: 1,
    iconKey: 'popular_post',
    isActive: true,
  },
  {
    name: 'Criador de Conteúdo',
    description: 'Tenha 3 posts populares (10+ curtidas cada)',
    category: AchievementCategory.SOCIAL,
    type: AchievementType.POPULAR_POST,
    targetValue: 3,
    iconKey: 'content_creator',
    isActive: true,
  },
  {
    name: 'Primeira Conversa',
    description: 'Inicie sua primeira conversa privada',
    category: AchievementCategory.SOCIAL,
    type: AchievementType.NEW_CONVERSATION,
    targetValue: 1,
    iconKey: 'first_conversation',
    isActive: true,
  },

  // Conquistas Pessoais
  {
    name: 'Primeiro Registro',
    description: 'Crie sua primeira entrada no diário',
    category: AchievementCategory.PERSONAL,
    type: AchievementType.DIARY_ENTRIES,
    targetValue: 1,
    iconKey: 'first_entry',
    isActive: true,
  },
  {
    name: 'Semana de Reflexão',
    description: 'Escreva 7 entradas no diário',
    category: AchievementCategory.PERSONAL,
    type: AchievementType.DIARY_ENTRIES,
    targetValue: 7,
    iconKey: 'week_reflection',
    isActive: true,
  },
  {
    name: 'Mês de Jornada',
    description: 'Escreva 30 entradas no diário',
    category: AchievementCategory.PERSONAL,
    type: AchievementType.DIARY_ENTRIES,
    targetValue: 30,
    iconKey: 'month_journey',
    isActive: true,
  },
  {
    name: 'Hábito de Escrita',
    description: 'Escreva 100 entradas no diário',
    category: AchievementCategory.PERSONAL,
    type: AchievementType.DIARY_ENTRIES,
    targetValue: 100,
    iconKey: 'writing_habit',
    isActive: true,
  },

  // Conquistas de Metas e Planos
  {
    name: 'Primeira Prática',
    description: 'Complete sua primeira prática de um plano',
    category: AchievementCategory.GOALS_PLANS,
    type: AchievementType.CONSECUTIVE_PRACTICES,
    targetValue: 1,
    iconKey: 'first_practice',
    isActive: true,
  },
  {
    name: 'Semana Consistente',
    description: 'Complete 7 práticas consecutivas',
    category: AchievementCategory.GOALS_PLANS,
    type: AchievementType.CONSECUTIVE_PRACTICES,
    targetValue: 7,
    iconKey: 'consistent_week',
    isActive: true,
  },
  {
    name: 'Dedicação Constante',
    description: 'Complete 30 práticas consecutivas',
    category: AchievementCategory.GOALS_PLANS,
    type: AchievementType.CONSECUTIVE_PRACTICES,
    targetValue: 30,
    iconKey: 'constant_dedication',
    isActive: true,
  },
  {
    name: 'Primeiro Plano Concluído',
    description: 'Complete seu primeiro plano de recuperação',
    category: AchievementCategory.GOALS_PLANS,
    type: AchievementType.PLAN_COMPLETION,
    targetValue: 1,
    iconKey: 'first_plan_completed',
    isActive: true,
  },
  {
    name: 'Progresso Constante',
    description: 'Complete 3 planos de recuperação',
    category: AchievementCategory.GOALS_PLANS,
    type: AchievementType.PLAN_COMPLETION,
    targetValue: 3,
    iconKey: 'constant_progress',
    isActive: true,
  },
  {
    name: 'Mestre da Recuperação',
    description: 'Complete 10 planos de recuperação',
    category: AchievementCategory.GOALS_PLANS,
    type: AchievementType.PLAN_COMPLETION,
    targetValue: 10,
    iconKey: 'recovery_master',
    isActive: true,
  },
  {
    name: 'Plano IA Concluído',
    description: 'Complete um plano criado pela IA',
    category: AchievementCategory.GOALS_PLANS,
    type: AchievementType.AI_PLAN_COMPLETION,
    targetValue: 1,
    iconKey: 'ai_plan_completed',
    isActive: true,
  },
  {
    name: 'Parceiro da IA',
    description: 'Complete 5 planos criados pela IA',
    category: AchievementCategory.GOALS_PLANS,
    type: AchievementType.AI_PLAN_COMPLETION,
    targetValue: 5,
    iconKey: 'ai_partner',
    isActive: true,
  },

  // Conquistas Gerais
  {
    name: 'Reflexão Profunda',
    description: 'Escreva uma reflexão profunda no diário',
    category: AchievementCategory.GENERAL,
    type: AchievementType.DEEP_REFLECTION,
    targetValue: 1,
    iconKey: 'deep_reflection',
    isActive: true,
  },
  {
    name: 'Pensador Profundo',
    description: 'Escreva 10 reflexões profundas',
    category: AchievementCategory.GENERAL,
    type: AchievementType.DEEP_REFLECTION,
    targetValue: 10,
    iconKey: 'deep_thinker',
    isActive: true,
  },
  {
    name: 'Primeira Consulta IA',
    description: 'Busque ajuda da IA pela primeira vez',
    category: AchievementCategory.GENERAL,
    type: AchievementType.AI_HELP_SEEKING,
    targetValue: 1,
    iconKey: 'first_ai_help',
    isActive: true,
  },
  {
    name: 'Usuário da IA',
    description: 'Busque ajuda da IA 10 vezes',
    category: AchievementCategory.GENERAL,
    type: AchievementType.AI_HELP_SEEKING,
    targetValue: 10,
    iconKey: 'ai_user',
    isActive: true,
  },
  {
    name: 'Colaborador da IA',
    description: 'Busque ajuda da IA 50 vezes',
    category: AchievementCategory.GENERAL,
    type: AchievementType.AI_HELP_SEEKING,
    targetValue: 50,
    iconKey: 'ai_collaborator',
    isActive: true,
  },
];
